name: Publish Release

on:
  release:
    types: [ created ]
  workflow_dispatch:
  
concurrency:
  group: "publish-release"
  cancel-in-progress: false

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}

jobs:
  publish-release:
    name: Publish Release

    runs-on: macOS-14

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish
        run: ./gradlew --no-configuration-cache publishAllPublicationsToMavenCentralRepository
